import serial
import time

uart = serial.Serial("/dev/ttyACM0",115200)
command = b'\x04' + int(0).to_bytes(2,'big',signed=True)
print(command)
uart.write(b'\x04' + int(0).to_bytes(2,'big',signed=True))
time.sleep(1)
command = b'\x04' + int(100).to_bytes(2,'big',signed=True)
print(command)
uart.write(b'\x04' + int(100).to_bytes(2,'big',signed=True))
time.sleep(1)
command = b'\x04' + int(75).to_bytes(2,'big',signed=True)
print(command)
uart.write(b'\x04' + int(75).to_bytes(2,'big',signed=True))
time.sleep(1)
command = b'\x04' + int(50).to_bytes(2,'big',signed=True)
print(command)
uart.write(b'\x04' + int(50).to_bytes(2,'big',signed=True))
time.sleep(1)
command = b'\x04' + int(25).to_bytes(2,'big',signed=True)
print(command)
uart.write(b'\x04' + int(25).to_bytes(2,'big',signed=True))
time.sleep(1)
command = b'\x04' + int(0).to_bytes(2,'big',signed=True)
print(command)
uart.write(b'\x04' + int(0).to_bytes(2,'big',signed=True))
time.sleep(1)
command = b'\x04' + int(-25).to_bytes(2,'big',signed=True)
print(command)
uart.write(b'\x04' + int(-25).to_bytes(2,'big',signed=True))
time.sleep(1)
command = b'\x04' + int(-50).to_bytes(2,'big',signed=True)
print(command)
uart.write(b'\x04' + int(-50).to_bytes(2,'big',signed=True))
time.sleep(1)
command = b'\x04' + int(-75).to_bytes(2,'big',signed=True)
print(command)
uart.write(b'\x04' + int(-75).to_bytes(2,'big',signed=True))
time.sleep(1)
command = b'\x04' + int(100).to_bytes(2,'big',signed=True)
print(command)
uart.write(b'\x04' + int(100).to_bytes(2,'big',signed=True))
time.sleep(1)
